#!/bin/sh

set -eu

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
ROOT_DIR=$(CDPATH= cd -- "$SCRIPT_DIR/.." && pwd)
ENV_FILE=${NESTTALK_ENV_FILE:-"$SCRIPT_DIR/.env"}
PODMAN=${PODMAN:-podman}

SERVER_ADDR=""
DATA_DIR="/opt/nesttalk/data"
REALITY_SNI="cloudflare.com"
REALITY_DEST="cloudflare.com:443"
SKIP_BUILD="${NESTTALK_SKIP_BUILD:-0}"

usage() {
  cat <<'EOF'
Usage:
  ./deploy/up.sh [--server-addr host:443] [--data-dir /opt/nesttalk/data]
                 [--reality-sni cloudflare.com] [--reality-dest cloudflare.com:443]
                 [--skip-build]

Behavior:
  - If deploy/.env does not exist, it is generated automatically.
  - All server-side images are built on the current host from source.
  - The pod is rendered and started, and the local-only CLI sidecar is launched.

Notes:
  - --server-addr is required only for the first run (when deploy/.env is absent).
  - Subsequent runs reuse deploy/.env and just rebuild/redeploy.
EOF
}

die() {
  echo "$*" >&2
  exit 1
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --server-addr)
      [ "$#" -ge 2 ] || die "--server-addr requires a value"
      SERVER_ADDR=$2
      shift 2
      ;;
    --data-dir)
      [ "$#" -ge 2 ] || die "--data-dir requires a value"
      DATA_DIR=$2
      shift 2
      ;;
    --reality-sni)
      [ "$#" -ge 2 ] || die "--reality-sni requires a value"
      REALITY_SNI=$2
      shift 2
      ;;
    --reality-dest)
      [ "$#" -ge 2 ] || die "--reality-dest requires a value"
      REALITY_DEST=$2
      shift 2
      ;;
    --skip-build)
      SKIP_BUILD=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      die "unknown argument: $1"
      ;;
  esac
done

command -v "$PODMAN" >/dev/null 2>&1 || die "podman is required"

generate_uuid() {
  cat /proc/sys/kernel/random/uuid
}

generate_hex() {
  bytes=$1
  od -An -tx1 -N "$bytes" /dev/urandom | tr -d ' \n'
}

build_singbox_image() {
  "$PODMAN" build -f "$SCRIPT_DIR/Containerfile.singbox" -t localhost/nesttalk-singbox:latest "$SCRIPT_DIR"
}

ensure_singbox_image() {
  if ! "$PODMAN" image exists localhost/nesttalk-singbox:latest >/dev/null 2>&1; then
    build_singbox_image
  fi
}

generate_reality_keys() {
  # sing-box prints "PrivateKey: <base64>\nPublicKey: <base64>" — match either
  # cased label so future minor sing-box releases keep working.
  key_output=$("$PODMAN" run --rm --entrypoint sing-box localhost/nesttalk-singbox:latest generate reality-keypair)
  reality_private=$(printf '%s\n' "$key_output" | awk -F': ' 'tolower($1) ~ /private[ ]?key/ {print $2}')
  reality_public=$(printf '%s\n' "$key_output" | awk -F': ' 'tolower($1) ~ /public[ ]?key/ {print $2}')
  [ -n "$reality_private" ] || die "failed to generate REALITY private key"
  [ -n "$reality_public" ] || die "failed to generate REALITY public key"
}

write_env_file() {
  [ -n "$SERVER_ADDR" ] || die "deploy/.env is missing; provide --server-addr host:443 for first-time setup"
  # .env persists TURN_SECRET + REALITY_PRIVATE_KEY — create it 0600.
  umask 077

  if [ "$SKIP_BUILD" -eq 1 ]; then
    ensure_singbox_image
  else
    build_singbox_image
  fi
  generate_reality_keys

  cat > "$ENV_FILE" <<EOF
# Generated by deploy/up.sh
# Optional legacy direct-API fallback. Leave empty for REALITY-only deployments.
API_BASE_URL=
NESTTALK_DATA_DIR=$DATA_DIR
TURN_SECRET=$(generate_hex 32)
TURN_REALM=nesttalk
LISTEN_ADDR=127.0.0.1:8080
REALITY_SERVER_ADDR=$SERVER_ADDR
REALITY_PUBLIC_KEY=$reality_public
REALITY_PRIVATE_KEY=$reality_private
REALITY_SHORT_ID=$(generate_hex 8)
REALITY_API_UUID=$(generate_uuid)
REALITY_TURN_UUID=$(generate_uuid)
REALITY_SNI=$REALITY_SNI
REALITY_DEST=$REALITY_DEST
API_REDIRECT=127.0.0.1:8080
# Per-request HTTP logging (metadata only). On by default; set to empty for a
# release deploy (NESTTALK_DEBUG= ./deploy/up.sh ... then re-render).
NESTTALK_DEBUG=${NESTTALK_DEBUG:-1}
# APNs VoIP push (incoming-call-while-closed). Leave KEY_ID/TEAM_ID empty to
# disable. The .p8 key is NOT stored here — supply it as a podman secret:
#   podman secret create nesttalk-apns-p8 deploy/.apns.p8
NESTTALK_APNS_KEY_ID=${NESTTALK_APNS_KEY_ID:-}
NESTTALK_APNS_TEAM_ID=${NESTTALK_APNS_TEAM_ID:-}
NESTTALK_APNS_TOPIC_VOIP=${NESTTALK_APNS_TOPIC_VOIP:-com.nesttalk.ios.voip}
NESTTALK_APNS_ENDPOINT=${NESTTALK_APNS_ENDPOINT:-api.push.apple.com:443}
EOF

  chmod 600 "$ENV_FILE"
  echo "generated $ENV_FILE"
}

if [ ! -f "$ENV_FILE" ]; then
  write_env_file
fi

set -a
. "$ENV_FILE"
set +a

if [ "$SKIP_BUILD" -eq 0 ]; then
  "$PODMAN" build -f "$SCRIPT_DIR/Containerfile.server" -t localhost/nesttalk-server:latest "$ROOT_DIR"
  "$PODMAN" build -f "$SCRIPT_DIR/Containerfile.cli" -t localhost/nesttalk-cli:latest "$ROOT_DIR"
  "$PODMAN" build -f "$SCRIPT_DIR/Containerfile.singbox" -t localhost/nesttalk-singbox:latest "$SCRIPT_DIR"
  "$PODMAN" build -f "$SCRIPT_DIR/Containerfile.coturn" -t localhost/nesttalk-coturn:latest "$SCRIPT_DIR"
fi

"$SCRIPT_DIR/render-pod.sh"

"$PODMAN" rm -f nesttalk-cli >/dev/null 2>&1 || true
"$PODMAN" pod rm -f nesttalk >/dev/null 2>&1 || true

"$PODMAN" play kube "$SCRIPT_DIR/pod.rendered.yaml"

# CLI sidecar runs outside the pod with --network none for stronger admin isolation.
# Admin RPC reaches the server only through the shared Unix-socket mount at
# /var/run/nesttalk/control.sock; it never uses the network and does not need a
# database-file mount for routine operations. The CLI container therefore does
# NOT appear in pod.rendered.yaml.
"$PODMAN" run -d --name nesttalk-cli --network none \
  -e REALITY_SERVER_ADDR="${REALITY_SERVER_ADDR}" \
  -e REALITY_PUBLIC_KEY="${REALITY_PUBLIC_KEY}" \
  -e REALITY_SHORT_ID="${REALITY_SHORT_ID}" \
  -e REALITY_API_UUID="${REALITY_API_UUID}" \
  -e REALITY_TURN_UUID="${REALITY_TURN_UUID}" \
  -e REALITY_SNI="${REALITY_SNI}" \
  --entrypoint sh -v "${NESTTALK_DATA_DIR}/run:/var/run/nesttalk:z" \
  localhost/nesttalk-cli:latest \
  -c 'trap : TERM INT; sleep infinity & wait'

echo
echo "NestTalk is up."
echo "Health: podman exec nesttalk-nesttalk-server wget -qO- http://127.0.0.1:8080/api/v1/health"
echo "Admin CLI: podman exec nesttalk-cli nesttalk-cli --socket /var/run/nesttalk/control.sock <command>"
