import XCTest
import CryptoKit
#if os(iOS)
@testable import NestTalk_iOS
#elseif os(macOS)
@testable import NestTalk_macOS
#endif

/// Gates the Swift hybrid cipher against the canonical interop vectors in
/// `test/crypto-interop/vectors.json` (generated by the Go reference,
/// `server/test/crypto-interop/go_roundtrip_test.go`). These guard
/// adversarial-review round 13's no-ship finding: the production crypto
/// must derive the HKDF info / AEAD AAD from the full routing context
/// (version + all five routing UUIDs), byte-identical to a conforming
/// peer — Apple-only round-trip tests cannot catch a wire-format drift.
final class CryptoInteropVectorsTests: XCTestCase {

    private struct Vector: Decodable {
        let name: String
        let version: Int
        let sender_user_id: String
        let sender_device_id: String
        let recipient_user_id: String
        let recipient_device_id: String
        let message_id: String
        let recipient_ml_kem_seed_hex: String
        let recipient_x25519_priv_hex: String
        let nonce_hex: String
        let plaintext_hex: String
        let hkdf_info_hex: String
        let symmetric_key_hex: String
        let ciphertext_hex: String
        let envelope_hex: String
    }

    private struct Vectors: Decodable {
        let spec_version: Int
        let vectors: [Vector]
    }

    private func loadVectors() throws -> [Vector] {
        // apple/NestTalkTests/<this file> → repo root is three parents up.
        let root = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()   // NestTalkTests
            .deletingLastPathComponent()   // apple
            .deletingLastPathComponent()   // repo root
        let url = root.appendingPathComponent("test/crypto-interop/vectors.json")
        let data = try Data(contentsOf: url)
        return try JSONDecoder().decode(Vectors.self, from: data).vectors
    }

    private func routing(_ v: Vector) -> EnvelopeRouting {
        EnvelopeRouting(
            version: UInt8(v.version),
            senderUserId: v.sender_user_id,
            senderDeviceId: v.sender_device_id,
            recipientUserId: v.recipient_user_id,
            recipientDeviceId: v.recipient_device_id,
            messageId: v.message_id
        )
    }

    /// The 96-byte HKDF-info / AAD blob must match the Go reference EXACTLY
    /// for every vector. This is the precise contract round 13 found
    /// violated (the prior code used a constant info + string AAD).
    func test_routing_info_blob_matches_reference_vectors() throws {
        let vectors = try loadVectors()
        XCTAssertFalse(vectors.isEmpty, "vectors.json must contain vectors")
        for v in vectors {
            let info = routing(v).infoBytes()
            XCTAssertEqual(info.count, EnvelopeRouting.infoLength, "[\(v.name)] info must be 96 bytes")
            XCTAssertEqual(info.hexString, v.hkdf_info_hex.lowercased(),
                           "[\(v.name)] HKDF info/AAD blob must be byte-identical to the Go reference")
        }
    }

    /// End-to-end: HybridCryptoService.open must recover the reference
    /// plaintext from the reference envelope using the conformant
    /// info/AAD. Gated to the first OS shipping ML-KEM in CryptoKit.
    func test_hybrid_open_decrypts_reference_envelopes() async throws {
        guard #available(iOS 26.0, macOS 26.0, *) else {
            throw XCTSkip("HybridCryptoService requires ML-KEM (iOS/macOS 26+)")
        }
        let vectors = try loadVectors()
        for v in vectors {
            guard
                let x25519Priv = Data(hexStringStrict: v.recipient_x25519_priv_hex),
                let mlkemSeed = Data(hexStringStrict: v.recipient_ml_kem_seed_hex),
                let envelopeBytes = Data(hexStringStrict: v.envelope_hex),
                let expectedPlaintext = Data(hexStringStrict: v.plaintext_hex)
            else {
                XCTFail("[\(v.name)] malformed hex in vector")
                continue
            }

            let bundle = HybridCryptoService.LocalKeyBundle(
                x25519Private: try Curve25519.KeyAgreement.PrivateKey(rawRepresentation: x25519Priv),
                mlkemPrivate: try MLKEM768.PrivateKey(seedRepresentation: mlkemSeed, publicKey: nil)
            )
            let svc = HybridCryptoService(bundle: bundle, selfUserId: v.recipient_user_id)

            let parsed = try WireEnvelope.parse(envelopeBytes)
            let routing = EnvelopeRouting(parsed: parsed)
            let envelope = Envelope(
                version: parsed.version,
                senderEphemeralX25519Pub: parsed.senderEphemeralX25519Pub,
                kemCiphertext: parsed.kemCiphertext,
                nonce: parsed.nonce,
                aad: routing.infoBytes(),
                ciphertext: Data(parsed.ciphertextWithTag.dropLast(16)),
                tag: Data(parsed.ciphertextWithTag.suffix(16))
            )
            let opened = try await svc.open(envelope, fromRecipient: CryptoRecipient(userId: v.sender_user_id), routing: routing)
            XCTAssertEqual(opened, expectedPlaintext, "[\(v.name)] hybrid open must recover the reference plaintext")
        }
    }
}

// MARK: - small test helpers

private extension Data {
    var hexString: String {
        map { String(format: "%02x", $0) }.joined()
    }

    /// Strict hex decoder (even length, valid digits) — nil on bad input.
    init?(hexStringStrict s: String) {
        guard s.count % 2 == 0 else { return nil }
        var out = [UInt8](); out.reserveCapacity(s.count / 2)
        var idx = s.startIndex
        while idx < s.endIndex {
            let next = s.index(idx, offsetBy: 2)
            guard let b = UInt8(s[idx..<next], radix: 16) else { return nil }
            out.append(b); idx = next
        }
        self = Data(out)
    }
}
